//! UI module: top-level window and (later) pages/widgets.

pub mod album_detail_page;
pub mod album_picker;
pub mod apply_to_media_list;
pub mod editor_panel;
pub mod empty_states;
pub mod glass_context_menu;
pub mod grid_css;
pub mod grid_row;
pub mod keyboard;
pub mod media_grid;
pub mod media_list;
pub mod mode_selector;
pub mod models;
pub mod photo_tile;
pub mod photos_page;
pub mod refresh_hub;
pub mod search_page;
pub mod section_header;
pub mod square_tile;
pub mod theme;
pub mod toasts;
pub mod trash_fallback;
pub mod trash_page;
pub mod viewer_page;
pub mod virtual_media_grid;
pub mod window;

pub use album_detail_page::AlbumDetailPage;
pub use album_picker::AlbumPickerDialog;
pub use editor_panel::EditorPanel;
pub use media_grid::MediaGrid;
pub use mode_selector::ModeSelector;
pub use photo_tile::PhotoTile;
pub use photos_page::PhotosPage;
pub use search_page::SearchPage;
pub use section_header::SectionHeader;
pub use square_tile::SquareTile;
pub use trash_page::TrashPage;
pub use viewer_page::{NavDelta, ViewerPage, NAV_POP};
pub use window::MainWindow;
